"""Add column brand_id in Item table

Revision ID: 69a9ea008418
Revises: 7a7539bdd9dd
Create Date: 2025-08-15 19:27:03.486147

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a9ea008418'
down_revision = '7a7539bdd9dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_item_brand', 'brand', ['brand_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint('fk_item_brand', type_='foreignkey')
        batch_op.drop_column('brand_id')

    # ### end Alembic commands ###
